j3k0/cordova-plugin-purchase

src/js/platforms/ios-adapter.js

I recently had an app rejected from the apple store for not having a Restore Previous Purchases button (though this functionality happened automatically on launch).
To get this feature to work properly I implemented these hooks.
The use case is:
If a user launches the app on a new device, but has not signed in with an apple ID yet, calling store.refresh() will prompt the user to login in or create an account. If the user cancels this screen (from failure or whatever reason) or succeeds in logging in I needed some way to display an indication and trigger actions. I couldn't find a pre-existing method to do so without adding these triggers.

Add triggers for hooking into restore failed or completed

---

src/android/com/smartmobilesoftware/util/IabHelper.java
src/js/platforms/ios-adapter.js
www/store-ios.js

The native call to getSkuDetails only supports max 20 entries. 
If you want to query more, you have to slices the SKUs in bundles of queries.

Updated querySKUDetails to suport more then 20

---

src/ios/InAppPurchase.h
src/ios/InAppPurchase.m

in certain occasions calling the addObserver multiple times, can lead to ui prompting user credentials too many times, holding a simple ref we could control this...

add property to hold observer ref, avoid calling multiple times

---

www/store-android.js

fix retrying store#refresh() error.
1. Turn off my WiFi connection.
2. Execute store#refresh(), then request failed on error. 
3. Turn on my WiFi connection.
4. Execute store#refresh() again. Though the connection valid, but request is failed with next error.
`{code: 6777019, message: "refresh failed - Billing plugin was not initialized"}`
I think that it should be suppressed to trigger the "re-refreshed" event on secondary store#refresh() while initialization is not complete.

fix retrying store#refresh() error.

---

src/ios/InAppPurchase.m
src/js/platforms/ios-adapter.js
www/store-ios.js

These commits fix #292 
Also set `static BOOL g_debugEnabled = NO;` by default, since setting `store.verbosity = store.DEBUG;` sets it to `YES`

Remove duplicate calls to downloading() promise

---

README.md
doc/windows.md
src/js/platforms/plugin-bridge.js
src/windows/InAppPurchaseProxy.js
www/store-windows.js

setTestMode on windows now takes callback args instead of a bool.
This fixes it loading the simulator xml file and adds the ability to handle when it's done loading the file contents.
Should fix #294

Fix testmode for windows

---

src/ios/InAppPurchase.m
www/store-ios.js

As the currencyCode returns null for iOS, I have extended the code to return this, as we need it for our current project for transaction capturing on our server. Kindly request to review and merge this with the master branch.

Add currencyCode to product details for iOS

---

src/js/platforms/ios-adapter.js

If user push cancel to signin iTunes Store, we get this WARNING.
```
WARNING:            storekitFinish@file:///.../PurchaseDemo.app/www/plugins/cc.fovea.cordova.purchase/www/store-ios.js:1162:36
file:///.../PurchaseDemo.app/www/plugins/cc.fovea.cordova.purchase/www/store-ios.js:1155:23
triggerWhenProduct@file:///.../PurchaseDemo.app/www/plugins/cc.fovea.cordova.purchase/www/store-ios.js:600:44
trigger@file:///.../PurchaseDemo.app/www/plugins/cc.fovea.cordova.purchase/www/store-ios.js:640:42
trigger@file:///.../PurchaseDemo.app/www/plugins/cc.fovea.cordova.purchase/www/store-ios.js:529:22
stateChanged@file:///.../PurchaseDemo.app/www/plugins/cc.fovea.cordova.purchase/www/store-ios.js:517:37
set@file:///.../PurchaseDemo.app/www/plugins/cc.fovea.cordova.purchase/www/store-ios.js:500:51 …
```

Fixed the case that product.transaction is null in storekitFinish

---

src/js/error.js

About iOS 8.
If store.order is called when the device is offline, SKPaymentTransactionStateFailed is occurred.
Then, if the device is iOS8.*, transaction.error is nil, errorText is undefined(cb.message is undefined) and we cannot catch this error through store.error callback.
I think we should catch above error through store.error callback with error message is "unknown error".
This pull request adds the case cb.code !== undefined and cb.message === undefined to call store.error callback.
Thanks.

fix to handle error message is nil

---

src/js/constants.js
src/js/product.js
www/store-android.js
www/store-ios.js
www/store-windows.js

This enables IAP for non-renewable subscriptions in iOS. You use them just like consumable IAP's. The UI is slightly different as is described in Apple docs. You must manage the subscription time period and sync across devices. See Apple doc here https://developer.apple.com/library/ios/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Products.html#//apple_ref/doc/uid/TP40008267-CH2-SW5
Use type `store.NON_RENEWING_SUBSCRIPTION` when registering a product.

Fix to allow non-renewable subscription purchases for iOS

---

doc/api.md
doc/ios.md
src/js/platforms/ios-adapter.js
src/js/product.js
www/store-ios.js

Full documentation on how to use iOS non-renewing subscriptions. Also added a little bit more error checking and correctly treated non-renewing subscription transactions like consumables in one step of the flow.

Non renewable subscription docs

---

src/ios/InAppPurchase.m
src/js/platforms/ios-adapter.js
www/store-ios.js

Addresses three issues I encountered on iOS:
1. Trigger product's error listener on store errors.
Currently, most errors (including purchase errors) only fire on the global store.error listener. This obscures which product caused the error.
NOTE: It looks like the same issue may apply to Android and Windows, although I haven't tested on those platforms yet. This request currently only covers iOS.
2. When finishing consumables and non-renewing subscriptions, clear transactions from product.transactions after calling finish.
Otherwise, transactions stay in product.transactions indefinitely, preventing future approved events for those transactions. This can come up if finish fails (e.g. due to network error).
3. In InAppPurchase.m, handle restored transactions that have a nil …

Changes to v6.0.0

---

src/android/com/smartmobilesoftware/util/IabHelper.java

Preventing crash when this error occurs:
com.smartmobilesoftware.util.IabHelper.queryPurchases (IabHelper.java:831)
com.smartmobilesoftware.util.IabHelper.queryInventory (IabHelper.java:576)
com.smartmobilesoftware.util.IabHelper.queryInventory (IabHelper.java:540)
com.smartmobilesoftware.util.IabHelper$2.run (IabHelper.java:635)
java.lang.Thread.run (Thread.java:818)

Preventing crash on java.lang.NullPointerException

---

src/android/com/smartmobilesoftware/inappbilling/InAppBillingPlugin.java
src/js/constants.js
src/js/order.js
src/js/platforms/plugin-adapter.js
src/js/platforms/plugin-bridge.js
src/js/product.js
www/store-android.js

Hi, here's an example of extending the use of additionalData. I rely on the developerPayload option and I need it to be sent from javascript. So I used the additionalData parameter to do this.
This pull request is based on my previous pull request.

Extend additionalData usage, add developer payload

---

src/js/platforms/plugin-adapter.js
src/js/product.js
www/store-android.js

Recreated, sorry.
My main usage for this is calculating the per month price for subscriptions. Having a float number of the price, regardless of currency and locale makes it really easy and clean to do it.
Might be useful for others, me included. Reference in Table 2 https://developer.android.com/google/play/billing/billing_reference.html

Added price_amount_micros to product data

---

README.md

The pdf that used to be linked no longer exists. The link I replaced it with is the new (as of iOS 11) place to find this information.

Update Link to iOS in-app purchase guidelines

---

doc/api.md
src/ios/InAppPurchase.m
src/js/platforms/ios-adapter.js
src/js/platforms/ios-bridge.js
src/js/store.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Opens iTunes' subscription management section.
Ref: https://developer.apple.com/library/archive/documentation/NetworkingInternet/Conceptual/StoreKitGuide/Chapters/Subscriptions.html#//apple_ref/doc/uid/TP40008267-CH7-SW5
Enabling Users to Manage Subscriptions
Rather than implementing your own subscription management UI, your
app can open the following URL:
https://buy.itunes.apple.com/WebObjects/MZFinance.woa/wa/manageSubscriptions
Opening this URL launches iTunes or iTunes Store and displays the
Manage Subscription page.

(ios) Add store.manageSubscriptions()

---

src/android/com/smartmobilesoftware/util/IabHelper.java

Found out some people added that into their IabHelper here:
https://stackoverflow.com/questions/38131475/inapp-billing-java-lang-securityexception-requires-read-phone-state
I never heard about the bug, but I suppose it should not hurt to add
this check.

(android) Backport NullPointer crash fix

---

src/js/product.js
www/store-android.js
www/store-ios.js
www/store-windows.js

The last update ([`Let receipt validator update product's transaction info`](https://github.com/j3k0/cordova-plugin-purchase/commit/c261c01bdd6f0fff29b0d08fbe5e4a43d3f1c0c7)) expects the validation-servers response to have a `data` field, which is not always the case.
This fix makes sure `data` it is defined.

fix: make sure response.data is set

---

src/js/index.d.ts

Update alias parameter of store.register method in type definitions to be optional to match actual implementation

Type definitions: Make store.register alias parameter optional

---

README.md

This plugin does not work 100% if the cordova-plugin-network-information is not installed. Therefore added a description to the readme.
Feed free to adjust the description or move it to another file.

Add info for recommended/required cordova plugin

---

src/js/index.d.ts

Adjust the once() method to have the same signature as the when() method.
Fix the parameter order of the when() method to match the actual implementation

Adjust typings for once() and when()

---

plugin.xml
src/ios/InAppPurchase.m
www/cordova-osx-polyfill.js

Hi I added macos support.
I avoided code duplication and, given the StoreKit is the same, with some preprocecessor ifs, I managed to share the same code with the iOS. On the JS side the code is exactly the same. So I linked directly the ios-js.
The only thing is the logs mentioning ios, i.e. "ios --> finishing" ...
I didnt want add logic just for the sake of log labelling, maybe can be changed with some common value "storekit" or "app store".
I tested consumable/non consumable. I don't have an app with subscriptions, so I didn't try them, but the storekit flow is the same, I think they should work fine.
Let me know what you think and if I have to edit something.

macos support

---

src/ios/InAppPurchase.m

Fixes the compilation on iOS, as `TARGET_OS_MAC` is defined also when building for iOS.
Ref: http://sealiesoftware.com/blog/archive/2010/8/16/TargetConditionalsh.html
The `#else` does the trick.

fix ios/macos compiler conditionals

---

src/ios/InAppPurchase.m
src/js/platforms/ios-adapter.js
src/js/platforms/ios-bridge.js
www/store-ios.js

(if it exists)
This can be used to determine if a non-consumable product has been newly
purchased or is already owned and therefore being re-purchased (i.e.
redeemed).
_Amended by @j3k0_: Rename field to `original_transaction_id`, to match
the Apple receipt field (so that it works the same as when the user uses
a receipt validation server)

(ios) Add original_transaction_id to product.transaction

---

doc/ios.md
src/ios/InAppPurchase.m
src/js/index.d.ts
src/js/platforms/ios-adapter.js
src/js/platforms/ios-bridge.js
test/src/js/iap.js
www/store-ios.js

This PR adds an option to disable automatic download of Hosted Content on the iOS platform.
The reason for this is, if like me you want to move away from Apple Hosted Content to self-hosting your own content, there's no way to remove or change an existing Apple IAP product to be non-hosted and therefore the hosted content will currently always be downloaded if it exists, even if you don't want it to be.
This PR adds the `omitHostedContentDownload` option which is specific to the iOS platform, for example:
store.omitHostedContentDownload = true;
store.refresh();

Add option to disable automatic download of hosted content on iOS.

---

src/js/validator.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Because `orders()` can happen outside the app, `applicationUsername` wasn't
always sent with validations.

Add applicationUsername to all validation requests

---

Makefile
doc/api.md
package-lock.json
package.json
plugin.xml
src/ios/InAppPurchase.h
src/ios/InAppPurchase.m
src/ios/SKProduct+LocalizedPrice.m
src/ios/SKProductDiscount+LocalizedPrice.h
src/ios/SKProductDiscount+LocalizedPrice.m
src/js/constants.js
src/js/metadata.js
src/js/order.js
src/js/platforms/ios-adapter.js
src/js/platforms/ios-bridge.js
src/js/platforms/plugin-adapter.js
src/js/product-internal.js
src/js/product.js
src/js/utils.js
src/js/validator.js
test/js/run.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Work on supporting iOS Discount Offers.
- add `product.discounts`
- update subscription statuses based on appStoreReceipt (requires a receipt validator that can validate the "application" product)
- introduce the `store.APPLICATION` product type
- introduce `store.verifyPurchases()` which will trigger a refresh of based on the appStoreReceipt on iOS. Good practice will be to call this when entering the "Subscription Offer" screens in the app.
- better detection of expired subscriptions.

iOS Discount Offers

---

doc/api.md
src/js/platforms/plugin-adapter.js
src/js/refresh.js
www/store-android.js
www/store-ios.js
www/store-windows.js

With this PR, `store.refresh()` returns a promise-like object with the following functions:
- `.completed(fn)` - Calls `fn` when the queue of previous purchases have been processed. At this point, all previously owned products should be in the approved state.
- `.finished(fn)` - Calls `fn` when all purchased in the approved state have been finished or expired.
In the case of the restore purchases call, you will want to hide any progress bar when the `finished` callback is called.
Example:
```js
function restorePurchases() {
showProgress();
store.refresh().finished(hideProgress);
}
```

(all) store.restore() callbacks

---

doc/api.md
src/js/platforms/ios-adapter.js
src/js/refresh.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Add `.failed()` and `.cancelled()` to the `refresh()` promise return value.
Ensuire `finished()` is called in all cases.

Refresh `.failed()` and `.cancelled()`

---

src/js/index.d.ts

Without this have I can't use plugin with typescript, because of following error:
```
Function type notation must be parenthesized when used in a union type.  TS1385
135 |     off(callback: Function): void;
136 |     order(id: string, additionalData?: null | IAdditionalData): void;
> 137 |     applicationUsername?: string | () => string;
^
138 |   }
```

Fix type chek error on tsc ^4.0.5

---

src/js/index.d.ts
src/js/utils.js
src/js/validator.js
www/store-android.js
www/store-ios.js
www/store-windows.js

You indicated in #1082 that a PR for this might be welcome.
-Add support for customHeaders in the validator url call.
I've done this by added a 3rd overload to the current string | function definition; which takes the form of an object with url and headers parameters.
`store.validator = { url: "https://...", headers: { authorization: "Bearer TOKEN" } }`
My specific use-case is I need the data server-side, so want to call fovea.cc validate rest API from the server-side.  I'm using firebase and want to authenticate against my validate url using the firebase bearer token.
---
```
cordova plugin add "https://github.com/j3k0/cordova-plugin-purchase.git#BRANCH_NAME_HERE"
```

Add support for custom headers in store.validator

---

src/android/cc/fovea/PurchasePlugin.java

Fixed a problem with onPurchasesUpdated that caused the list of purchases to become null and a nullpointer.
We actually ran this plugin in production and were experiencing crashes due to Nullpointer as attached in crashlytics.
[crash.txt](https://github.com/j3k0/cordova-plugin-purchase/files/9949179/crash.txt)
- Added check if purchases is not null when BillingResponseCode.OK is returned by onPurchasesUpdated.
---
```
cordova plugin add "https://github.com/masatada-kurihara/cordova-plugin-purchase.git#fix/onPurchasesUpdated-nullpointer"
```

fix: Fixed a problem with onPurchasesUpdated that caused the list of purchases to become null and a nullpointer.

---

src/ts/platforms/apple-appstore/appstore-adapter.ts
www/store.js

It's a tentative fix based on logs provided in the report (email), the issue hasn't occured here.
Here's the log:
```
[Debug] skin:iap LOG +26ms – "[CdvPurchase.AppleAppStore.Bridge] DEBUG: processing pending transactions" (main.a0051878.js, line 2)
[Debug] skin:iap [store] done +1ms (main.a0051878.js, line 2)
[Debug] skin:iap LOG +148ms – "[CdvPurchase.AppleAppStore] DEBUG: emitAppReceipt()" (main.a0051878.js, line 2)
[Debug] skin:iap LOG +0ms – "[CdvPurchase.AppleAppStore] DEBUG: using cached appstore receipt" (main.a0051878.js, line 2)
[Debug] skin:iap LOG +0ms – "[CdvPurchase.AppleAppStore] DEBUG: loading appstore receipt..." (main.a0051878.js, line 2)
[Debug] skin:iap LOG +0ms – "[CdvPurchase.AppleAppStore.Bridge] DEBUG: loading appStoreReceipt" (main.a0051878.js, line 2)
[Debug] …
```

Fix no appStoreReceipt on iOS App first launch

---

src/android/cc/fovea/PurchasePlugin.java
src/ts/platforms/google-play/googleplay-adapter.ts
www/store.js

- This is a proposed fix for issue #1364 
- In PurchasePlugin.java `callSuccess()` and `callError()` were not called after a product is consumed. Though I was unsure what message to pass in callError, I opted to use [BillingResult.getDebugMessage()](https://developer.android.com/reference/com/android/billingclient/api/BillingResult#getDebugMessage())  but to be honest I have no idea what kind of message this returns.
- In googleplay-adapter.ts the transaction state was not set to `TransactionState.FINISHED`, following the same appstore-adapter.ts convention I figured that was needed.

(Android) Fix: transactions do not finish after consuming a product

---

www/store.d.ts

- Angular version 12.2.6 which uses typescript 4.2.4 cannot understand syntax of version 4.7, now it can.

Add typescript 4.2.4 support

---

www/store.d.ts

- This adds typings for the success callback of getPurchases of Android bridge
---
```
cordova plugin add "https://github.com/platogo/cordova-plugin-purchase#google-getPurchases-typings"
```
Create the Android bridge and call the function: 
```
const androidBridge = new CdvPurchase.GooglePlay.Bridge.Bridge()
// call androidBridge.buy
androidBridge.getPurchases((products) => {
console.log('getPurchases', products)
}, () => console.log('error'))
```

Improve typings for getPurchases

---

src/ts/store.ts

I think the function to return the applicationUsername should also be able to return undefined (i.e. the default behavior should be applied), as it is also possible to set undefined directly.
-
-
---
```
cordova plugin add "https://github.com/j3k0/cordova-plugin-purchase.git#BRANCH_NAME_HERE"
```

applicationUsername function should accept undefined as return value

---

src/ts/internal/expiry-monitor.ts
src/ts/platforms/google-play/googleplay-adapter.ts
src/ts/platforms/google-play/googleplay-bridge.ts
src/ts/store.ts

Fixes issue #1632 where cancelled subscriptions on Android are not properly reflected in the `owned` flag when calling `store.update()`. Even after a subscription is cancelled and its period expires, the `owned` flag incorrectly remains `true`.
This PR implements a comprehensive solution that addresses the issue on multiple levels:
- Added `expiryTimeMillis` to the Purchase interface in the Google Play bridge
- Enhanced the `Transaction.refresh` method to correctly parse and set the `expirationDate` from this data
- Improved the `onPurchasesUpdated` method to update expiration dates for ALL subscriptions
- Enabled the built-in `ExpiryMonitor` to track local receipt expirations when no validator is configured
- Enhanced the monitor to automatically refresh purchase data when subscriptions …

(googleplay) Fix cancelled subscriptions not properly reflected in owned flag

---

README.md
doc/multi-quantity-purchases.md
src/android/cc/fovea/PurchasePlugin.java
src/ts/platforms/google-play/googleplay-adapter.ts
src/ts/platforms/google-play/googleplay-bridge.ts
src/ts/transaction.ts

This PR implements support for multi-quantity consumable purchases on the Google Play platform. This feature allows users to buy multiple quantities of the same consumable product in a single transaction, addressing issue #1629.
1. Updated the Android native code to properly expose the quantity field from Google Play purchase objects
2. Added documentation for the quantity field in the Transaction interface and GooglePlay Bridge Purchase interface
3. Improved the TypeScript transaction class to include the quantity field
4. Added comprehensive documentation on how to use the multi-quantity purchases feature
5. Updated README.md to include multi-quantity purchases in the features table
Fixes #1629

Add support for multi-quantity purchases on Android

---

src/ts/platforms/google-play/googleplay-adapter.ts
src/ts/store.ts
src/ts/types.ts
src/ts/validator/verified-receipt.ts

This PR addresses issue #1638 by improving how the plugin handles transactions that have already been acknowledged or consumed by a custom receipt validation server. The changes help prevent redundant finish operations that could cause errors when a backend has already processed purchases.
1. Added `isAcknowledged` and `isConsumed` properties to the `VerifiedPurchase` interface
2. Enhanced the `Store.finish()` method to check if transactions have already been processed according to receipt validation
3. Added platform-specific control via `canSkipFinish` flag to ensure safe operation across different platforms
4. Set `canSkipFinish = true` for Google Play, which allows skipping redundant finish operations
5. Updated transaction state handling to mark skipped transactions as FINISHED
When …

Fix redundant finish operations for transactions processed by validator
