j3k0/cordova-plugin-purchase

doc/api.md
doc/example.js

As the title suggest, a simple pull request to remove the documentation for functions that do not exist.
Caused some confusion for me at least.

[docs] Remove references to functions that do not exist

---

plugin.xml

FIX for Cordova in Visual Studio 2015 (ability to install plugin)

plugin.xml is not well-formed

---

src/ios/InAppPurchase.m

just the replacement mentioned on: https://github.com/j3k0/cordova-plugin-purchase/issues/218

replace deprecated base64EncodedString

---

src/android/com/smartmobilesoftware/inappbilling/InAppBillingPlugin.java

catch IllegalStateException

---

.gitignore
README.md
doc/api.md
doc/contributor-guide.md
doc/ios.md
plugin.xml
src/ios/FileUtility.h
src/ios/FileUtility.m
src/ios/InAppPurchase.h
src/ios/InAppPurchase.m
src/js/constants.js
src/js/platforms/ios-adapter.js
src/js/platforms/ios-bridge.js
src/js/product-internal.js
src/js/product.js
src/js/register.js
src/js/store.js
src/js/when.js
www/store-android.js
www/store-ios.js

This version of the iOS plugin will detect if a non-consumable in-app product has associated Apple-hosted content upon successful payment confirmation, and proceed to download and deploy the content to the app's "Documents" folder, where it is accessible to Cordova via the File API.

Apple-hosted downloadable content

---

src/js/platforms/plugin-adapter.js
www/store-android.js
www/store-windows.js

Changed the name of the property but not the references.
This also fixes #262

Fix up the adapter references for windows and android

---

src/js/platforms/plugin-adapter.js
src/js/platforms/windows-productdata.js
www/store-android.js
www/store-windows.js

Fix title and price according to [ProductListing class](https://msdn.microsoft.com/en-US/library/windows/apps/windows.applicationmodel.store.productlisting.aspx)
Also add minor fix to properly trigger "cancelled" event when purchase cancelled from initiated state

Fix price for winphone and unhandled cancel of purchase from initiated state

---

doc/windows.md
plugin.xml
src/js/platforms/android-productdata.js
src/js/platforms/plugin-adapter.js
src/js/platforms/windows-productdata.js
src/js/store.js
src/windows/InAppPurchaseProxy.js
www/store-android.js
www/store-windows.js

Separated out the iabGetPurchases function for Android and Windows to load the windows products in properly.
Also a few docs updates.
This is for Issue #294

[Windows] Fix for loading non-consumable purchases

---

src/js/platforms/plugin-adapter.js
src/js/platforms/plugin-bridge.js
src/js/platforms/windows-productdata.js
src/windows/InAppPurchaseProxy.js
www/store-windows.js

This pull request is in reference to: #456 and #457.
Here are the itemized changes:
1. The productLicenses were not being loaded from the Windows Store. This was only populated in `setTestMode()` when you were using the sandbox.
1. The subscribe function was calling `this.buy`, but `this` is the javascript Window object. Calling buy on `this.inappbilling` fixed this. Also passed the productId to the buy function instead of the args list.
1. `consumePurchase` in InAppPurchaseProxy.js was expecting the list of args to contain the transactionId, however it was not being passed. Now before the transaction is cleared from the product when it reaches the `finished` state the transaction object is stored in a local variable so that its ID can be passed to the consumePurchase call.
1. The `buy` …

Changes for durable and consumable purchases on Windows 10.

---

doc/api.md
src/android/com/android/vending/billing/IInAppBillingService.aidl
src/android/com/smartmobilesoftware/inappbilling/InAppBillingPlugin.java
src/android/com/smartmobilesoftware/util/IabHelper.java
src/js/constants.js
src/js/order.js
src/js/product.js
www/store-android.js

Accorrding to android API:
[android developer](https://developer.android.com/google/play/billing/billing_reference.html#upgrade-getBuyIntentToReplaceSkus)
Tested for production in our App

Added ability in android to upgrade an existing user subscription

---

src/js/constants.js
src/js/platforms/plugin-adapter.js
src/js/platforms/plugin-bridge.js
www/store-android.js

Hi. I ported the store-android.js changes from the subscription update functionality https://github.com/j3k0/cordova-plugin-purchase/commit/40ec181a39f4381b9189e11e3b52bd4217f47bfe to the source javascript files. This pull request makes the subscription work again. I also added a missing curly bracket somewhere in there.

Fix subscription update

---

src/js/validator.js

Fixes documentation that was meant to be fixed by https://github.com/j3k0/cordova-plugin-purchase/pull/320 but in the right place.

Fix error in validator docs

---

plugin.xml

this should fix the the probelms with cordova-android@7++

Fix: correct path to aidl

---

src/js/index.d.ts

Fixes https://github.com/j3k0/cordova-plugin-purchase/issues/465
These come from https://github.com/werk85/typed-cordova-plugin-purchase

Add typescript definitions.

---

package.json
plugin.xml

Dexus patch android.aidl fix

---

src/android/com/smartmobilesoftware/inappbilling/InAppBillingPlugin.java

This should fix the problem with the null pointers in java for android.

Fix: This should fix the bug with the null pointer

---

doc/api.md
src/ios/InAppPurchase.m
src/js/platforms/ios-adapter.js
src/js/product.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Added numeric field in order to pass directly to analytics

Added 'priceMicros' field for Product on iOS

---

.travis.yml

Greatly inspired from cordova-plugin-camera's setup:
https://raw.githubusercontent.com/apache/cordova-plugin-camera/master/.travis.yml

Test more different configurations with Travis CI

---

.travis.yml
plugin.xml
scripts/androidBeforeInstall.js
src/android/billing_key_param.xml
test/run.sh

Install was failing (and is now fixed) on my setup:
* cordova: 8.1.1
* cordova-android: 7.1.1
Ref #729
Needs more testing, I'll look into travis.

Fix android install on android-studio projects

---

src/android/com/smartmobilesoftware/util/IabHelper.java

See:
* https://stackoverflow.com/questions/38131475/inapp-billing-java-lang-securityexception-requires-read-phone-state
* https://github.com/googlesamples/android-play-billing/issues/26

(android) Fix #732 - Requires READ_PHONE_STATE

---

package.json
src/js/index.d.ts

Fixed Typescript types.

---

src/js/index.d.ts

Calling ready without parameter returns the ready status of the store

Update type definitions

---

doc/api.md
src/js/platforms/plugin-adapter.js
src/js/platforms/windows-productdata.js
src/js/product.js
src/js/store.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Auto-refresh purchases every 24h

---

src/js/index.d.ts

More type definition changes 😃 
Added once and when method signature for cases without product (e.g. refresh-completed event)

Update type definitions for once() and when()

---

src/android/com/smartmobilesoftware/util/IabHelper.java

(android) Backport IabHelper ANR fix from frostwire

---

doc/ios.md
src/ios/InAppPurchase.m
src/js/index.d.ts
src/js/platforms/ios-adapter.js
src/js/platforms/ios-bridge.js
test/src/js/iap.js
www/store-ios.js

...disable downloading hosted content on iOS.

(ios) Add disableHostedContent option

---

.travis.yml
package-lock.json
package.json
plugin.xml
test/run.sh

* test more cordova-[android/ios/osx] platforms
* test osx build
* better detect failing builds

Update travis-ci tests

---

src/android/com/smartmobilesoftware/inappbilling/InAppBillingPlugin.java
src/android/com/smartmobilesoftware/util/IabHelper.java

[ANDROID]: Add defensive try/catch blocks to prevent unhandled exceptions causing app crashes

---

doc/api.md
src/js/order.js
src/js/platforms/plugin-adapter.js
src/js/product.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Especially useful on android, so `oldSku` can be set automatically.

Add support for subscription groups

---

src/android/cc/fovea/PurchasePlugin.java

To test this branch:
```
cordova plugin add "https://github.com/j3k0/cordova-plugin-purchase.git#fix_android_cancellation"
```

(android) Fix reporting purchase cancellation

---

src/js/index.d.ts

Add methods update, manageSubscriptions and manageBilling to IStore.

Added missing methods to TypeScript definition

---

doc/api.md
doc/contributor-guide.md
src/ios/InAppPurchase.m
src/js/platforms/ios-adapter.js
src/js/platforms/ios-bridge.js
src/js/product-internal.js
src/js/product.js
www/store-android.js
www/store-ios.js
www/store-windows.js

Support for [Ask to Buy](https://support.apple.com/en-us/HT201089)
Can anyone test this? Please report here

(ios) Add support for deferred purchases

---

doc/android.md

Update docs link

---

doc/api.md
plugin.xml
src/android/cc/fovea/PurchasePlugin.java
src/js/index.d.ts
src/js/order.js
src/js/platforms/ios-adapter.js
src/js/platforms/plugin-adapter.js
src/js/platforms/plugin-bridge.js
src/js/store.js
www/store-android.js
www/store-ios.js
www/store-windows.js

- Ugrade to Google Play Billing library v4.0
---
```
cordova plugin add "https://github.com/j3k0/cordova-plugin-purchase.git#play-billing-v4"
```

Play billing v4
